-- Rumai yn this file once in the Supabase SQL Editor.
-- The service role is used only by the server-side refresh job.

create extension if not exists pgcrypto;

create table if not exists public.scrape_runs (
  id uuid primary key default gen_random_uuid(),
  fetched_at timestamptz not null,
  source_url text not null,
  counts jsonb not null default '{}'::jsonb,
  errors jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.matches (
  fixture_page_id text primary key,
  match_num text not null,
  league text not null,
  home text not null,
  away text not null,
  kickoff text not null,
  match_date text not null,
  match_time text not null,
  is_end boolean not null default false,
  is_active boolean not null default true,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists matches_kickoff_idx on public.matches (kickoff);
create index if not exists matches_active_idx on public.matches (is_active, is_end);

create table if not exists public.odds_snapshots (
  id bigint generated by default as identity primary key,
  scrape_run_id uuid not null references public.scrape_runs(id) on delete cascade,
  fixture_page_id text not null references public.matches(fixture_page_id) on delete cascade,
  one_x_two jsonb not null default '{}'::jsonb,
  handicap_three_way jsonb not null default '{}'::jsonb,
  half_full jsonb not null default '{}'::jsonb,
  scores jsonb not null default '{}'::jsonb,
  total_exact jsonb not null default '{}'::jsonb,
  deep_market jsonb,
  captured_at timestamptz not null default now()
);

create index if not exists odds_snapshots_fixture_idx
  on public.odds_snapshots (fixture_page_id, captured_at desc);

create table if not exists public.match_reports (
  fixture_page_id text primary key references public.matches(fixture_page_id) on delete cascade,
  generated_at timestamptz not null default now(),
  primary_pick text,
  handicap_pick text,
  goals_pick text,
  xg_home numeric(5, 2),
  xg_away numeric(5, 2),
  xg_total numeric(5, 2),
  score_top3 jsonb not null default '[]'::jsonb,
  report jsonb not null
);

-- Keep the tables private. Server routes use SUPABASE_SERVICE_ROLE_KEY,
-- and public read policies can be added later together with user accounts.
alter table public.scrape_runs enable row level security;
alter table public.matches enable row level security;
alter table public.odds_snapshots enable row level security;
alter table public.match_reports enable row level security;

-- Allow the server-side service role to write refresh results.
grant usage on schema public to service_role;
grant all privileges on table public.scrape_runs, public.matches,
  public.odds_snapshots, public.match_reports to service_role;
grant usage, select on all sequences in schema public to service_role;
